export CONFIG_NUMCPUS?=13
export CONFIG_QEMU?=qemu-system-$(CONFIG_ARCH)
export CONFIG_OUTPUT=$(PWD)/output/$(CONFIG_NAME)
export CONFIG_STAGING=$(CONFIG_OUTPUT)/staging
export CROSS_COMPILE=$(CONFIG_CROSS_COMPILE)
export CC=$(CROSS_COMPILE)gcc
export CXX=$(CROSS_COMPILE)g++
export LD=$(CROSS_COMPILE)ld
export AR=$(CROSS_COMPILE)ar
export STRIP=$(CONFIG_CROSS_COMPILE)strip
export CFLAGS+=-O2 -g -I$(CONFIG_STAGING)/include -I$(CONFIG_STAGING)/usr/include
export CXXFLAGS+=-O2 -g -I$(CONFIG_STAGING)/include -I$(CONFIG_STAGING)/usr/include
export LDFLAGS+=-L$(CONFIG_STAGING)/lib -L$(CONFIG_STAGING)/usr/lib
